FROM python:3.10-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    cmake \
    g++ \
    wget \
    unzip \
    libopenblas-dev \
    libx11-dev \
    libgtk-3-dev \
    && apt-get clean

# Install Python dependencies
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copy your app
COPY . /app
WORKDIR /app

# Run your Flask app
CMD ["python", "app.py"]
